# typed: false
# frozen_string_literal: true

# Generated by dev/scripts/update_homebrew_formula.sh — do not edit checksums by hand.
# Re-run the script after each release.

class Rivet < Formula
  desc "CLI to export PostgreSQL and MySQL to Parquet/CSV (local, S3, GCS)"
  homepage "https://github.com/panchenkoai/rivet"
  version "0.18.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/panchenkoai/rivet/releases/download/v0.18.0/rivet-v0.18.0-aarch64-apple-darwin.tar.gz"
      sha256 "b9f097f59b1a0f47e3cde75e4520b482d963dc9db60088cb8b0c0db3298eb5a6"
    end
    on_intel do
      url "https://github.com/panchenkoai/rivet/releases/download/v0.18.0/rivet-v0.18.0-x86_64-apple-darwin.tar.gz"
      sha256 "cbe8a157ae3265134419e5233f4e24d43897ab0935cd23d2a276b7ef29c27999"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/panchenkoai/rivet/releases/download/v0.18.0/rivet-v0.18.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "1b8166396362b278fb8516a2cda6b35a1913a74501b197ff90bda023400a2b91"
    end
    on_intel do
      url "https://github.com/panchenkoai/rivet/releases/download/v0.18.0/rivet-v0.18.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "19d081768356191ab564f46fe900346c1f88b42c4e8b1e0810bec404808178a1"
    end
  end

  def install
    # Both binaries shipped from 0.6.0 onwards.
    bin.install "rivet"
    bin.install "rivet-mcp" if File.exist?("rivet-mcp")
  end

  test do
    system "#{bin}/rivet", "--version"
  end
end
