# typed: false
# frozen_string_literal: true

# Generated by dev/scripts/update_homebrew_formula.sh — do not edit checksums by hand.
# Re-run the script after each release.

class Rivet < Formula
  desc "CLI to export PostgreSQL and MySQL to Parquet/CSV (local, S3, GCS)"
  homepage "https://github.com/panchenkoai/rivet"
  version "0.14.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/panchenkoai/rivet/releases/download/v0.14.0/rivet-v0.14.0-aarch64-apple-darwin.tar.gz"
      sha256 "a43db0b19c616789ad0b913aaebdf78fb84003de1dcde297d9c8b0d03e7959ce"
    end
    on_intel do
      url "https://github.com/panchenkoai/rivet/releases/download/v0.14.0/rivet-v0.14.0-x86_64-apple-darwin.tar.gz"
      sha256 "0fb235180f32cbec0aa083694923d040bb8079243f5116ffda85b81bc9c45842"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/panchenkoai/rivet/releases/download/v0.14.0/rivet-v0.14.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "606b50faccf8de701d50aa88ff2f203968be53cb9e9c0050fd704f8d6b87d886"
    end
    on_intel do
      url "https://github.com/panchenkoai/rivet/releases/download/v0.14.0/rivet-v0.14.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "be78f8e1bb2428836a744896690afffaadfaa518cce89793405fe1025a8a6da8"
    end
  end

  def install
    # Both binaries shipped from 0.6.0 onwards.
    bin.install "rivet"
    bin.install "rivet-mcp" if File.exist?("rivet-mcp")
  end

  test do
    system "#{bin}/rivet", "--version"
  end
end
